services:
  db:
    container_name: todo-app-db
    image: postgres:16
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    container_name: todo-app-web
    build: .
    volumes:
      - .:/todo-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dbuser:dbpassword@db:5432/todo
      - SESSION_SECRET="random123"
    command: >
      sh -c "npm run db:push:seed &&
             npm run build &&
             npm start"
volumes:
  pgdata:
